apiVersion: v1
kind: Namespace
metadata:
  name: anomaly-detection
---
apiVersion: v1
kind: Service
metadata:
  name: anomaly-api-service
  namespace: anomaly-detection
  labels:
    app: anomaly-api
spec:
  type: NodePort
  selector:
    app: anomaly-api
  ports:
    - port: 80
      targetPort: 8089
      nodePort: 30089