name: CI - Train and evaluate model

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'requirements.txt'
  workflow_dispatch:

jobs:
  train:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          rm -rf venv
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Train model and log to MLflow
        env:
          MLFLOW_TRACKING_URI: http://localhost:5555
          DATA_DIR: data/train
          EXPERIMENT_NAME: network-anomaly-detection
          MODEL_NAME: network-anomaly-svm
        run: |
          source venv/bin/activate
          cd src
          python train.py

      - name: Upload training logs
        uses: actions/upload-artifact@v4
        with:
          name: training-logs
          path: src/*.log
          if-no-files-found: ignore